const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("pennyworth", {
  getRuntimeConfig: () => ipcRenderer.invoke("pennyworth:get-runtime-config"),
  setProfile: (profileId) => ipcRenderer.invoke("pennyworth:set-profile", profileId),
  getSettings: () => ipcRenderer.invoke("pennyworth:get-settings"),
  getProviderHealth: (payload) => ipcRenderer.invoke("pennyworth:get-provider-health", payload),
  listOllamaModels: (payload) => ipcRenderer.invoke("pennyworth:list-ollama-models", payload),
  listOpenAIModels: (payload) => ipcRenderer.invoke("pennyworth:list-openai-models", payload),
  listGeminiModels: (payload) => ipcRenderer.invoke("pennyworth:list-gemini-models", payload),
  saveSettings: (payload) => ipcRenderer.invoke("pennyworth:save-settings", payload),
  getSystemContext: () => ipcRenderer.invoke("pennyworth:get-system-context"),
  listDisplays: () => ipcRenderer.invoke("pennyworth:list-displays"),
  captureScreen: (payload) => ipcRenderer.invoke("pennyworth:capture-screen", payload),
  ask: (payload) => ipcRenderer.invoke("pennyworth:ask", payload),
  cancelAgent: (sessionId) => ipcRenderer.invoke("pennyworth:cancel-agent", sessionId),
  onTraceEvent: (handler) => ipcRenderer.on("pennyworth:trace-event", (event, arg) => handler(arg)),
  windowMinimize: () => ipcRenderer.invoke("pennyworth:window-minimize"),
  windowMaximizeToggle: () => ipcRenderer.invoke("pennyworth:window-maximize-toggle"),
  windowClose: () => ipcRenderer.invoke("pennyworth:window-close"),
  onSummoned: (handler) => ipcRenderer.on("pennyworth:summoned", handler),
  listSessions: (options) => ipcRenderer.invoke("pennyworth:list-sessions", options),
  loadSession: (sessionId, options) => ipcRenderer.invoke("pennyworth:load-session", sessionId, options),
  newSession: () => ipcRenderer.invoke("pennyworth:new-session"),
  onSessionUpdated: (handler) => ipcRenderer.on("pennyworth:session-updated", (_event, payload) => handler(payload)),
  onSessionRenamed: (handler) => ipcRenderer.on("pennyworth:session-renamed", (_event, payload) => handler(payload)),
  renameSession: (sessionId, title) => ipcRenderer.invoke("pennyworth:rename-session", { sessionId, title }),
  deleteSession: (sessionId) => ipcRenderer.invoke("pennyworth:delete-session", sessionId),
  bootstrapOllama: () => ipcRenderer.invoke("pennyworth:bootstrap-ollama"),
  bootstrapPullModel: (modelName) => ipcRenderer.invoke("pennyworth:bootstrap-pull-model", modelName),
  bootstrapSetDefaultProvider: (provider, model) => ipcRenderer.invoke("pennyworth:bootstrap-set-default-provider", provider, model),
  onBootstrapProgress: (handler) => ipcRenderer.on("pennyworth:bootstrap-progress", (event, arg) => handler(arg)),
  showNativeNotification: (payload) => ipcRenderer.invoke("pennyworth:show-native-notification", payload),
  vaultStatus: () => ipcRenderer.invoke("pennyworth:vault-status"),
  vaultSetup: (passphrase) => ipcRenderer.invoke("pennyworth:vault-setup", passphrase),
  vaultUnlock: (passphrase) => ipcRenderer.invoke("pennyworth:vault-unlock", passphrase),
  transcribeAudio: (payload) => ipcRenderer.invoke("pennyworth:transcribe-audio", payload),
  sendAudioStreamChunk: (payload) => ipcRenderer.send("pennyworth:audio-stream-chunk", payload),
  stopAudioStream: () => ipcRenderer.send("pennyworth:audio-stream-stop"),
  onVoiceStatus: (handler) => ipcRenderer.on("pennyworth:voice-status", (_event, arg) => handler(arg)),
  onLiveTranscriptPartial: (handler) => ipcRenderer.on("pennyworth:live-transcript-partial", (_event, arg) => handler(arg)),
});
